module.exports = {
  equal: 'equal',
  in: 'in',
  any: 'any',
  all: 'all',
  icontains: 'icontains',
  contains: 'contains',
  starts_with: 'starts_with',
  istarts_with: 'istarts_with',
  ends_with: 'ends_with',
  iends_with: 'iends_with',
  year: 'year',
  month: 'month',
  day: 'day',
  week_day: 'week_day',
  regex: 'regex',
  range: 'range',
  gt: 'gt',
  lt: 'lt',
  gte: 'gte',
  lte: 'lte',
  is_null: 'is_null',
  is_not_null: 'is_not_null',
  eq: 'eq'
}